name: 'build-test'
on: # rebuild any PRs and main branch changes
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
      - uses: josStorer/get-current-time@v2.1.0
        id: current-time
        with:
          format: YYYYMMDD-HH
          utcOffset: "+08:00"
      - uses: ./
        with:
          sendkey: ${{ secrets.sendkey }}
          title: "server酱Action更新啦 ${{ steps.current-time.outputs.formattedTime }}"

